### ISSUE TITLE
Make controls in ardour sliders

### ISSUE THREAD

**Issue by spectromas** [ssj71/rkrlv2#27]
Is it by design that the plugin controls in ardour are left/right click buttons? They are quite tedious to use unless I'm missing some shortcut to make movements faster. 

Is there any chance they can be changed to sliders instead?

**Comment by ssj71** [comment]
It's because they are integer values and ardour handles them with spinboxes rather than sliders. Some other hosts still use sliders, but in ardour if you use the shift and control (or maybe alt?) keys while going up or down you get bigger movement. I agree its not very useable (though those shortcuts help a LOT), but fixing it is a bit outside the scope of this project.

I plan to eventually make a rkrv2 series that will improve on the originals, breaking backward compatibility. These will use float values and will have sliders. That's going to be a long way down the road, though I'm curious which effects you are most interested in and I could try to prioritize those.

Thanks for using these though and for submitting the bug even though its a wontfix for now. Let me know if you find other issues or workflow suggestions.

**Comment by spectromas** [comment]
The shift and control clicking makes it much easier to use, thanks for the tip. The ones I was originally most interested in were the modulation plugins (analog phaser, dual flanger, flanger/chorus), they sound really good but I've been playing with some of the others and they all seem to be great, the echo and echotron are very useful for me. The distortion sounds really good as well.
